services:
  cat:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  dog:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  nginx:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
        reservations:
          cpus: "0.05"
          memory: 32M

  prometheus:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

  grafana:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

  node-exporter:
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M

  cadvisor:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  portainer:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
