{
 "title": "API Docker Stack",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes HTTP / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total requêtes reçues",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU process Node.js (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"api-cat|api-dog\"}[1m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Mémoire RSS Node.js (MB)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"api-cat|api-dog\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Node.js (MB)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"api-cat|api-dog\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM système (Go)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "RAM utilisée"
    }
   ]
  }
 ]
}